Repository graphql-python/graphene, pull requests merged in 2019-06, with the labels that each got.

#983 v3.0 - remove Python 2.x from build
  .travis.yml
  graphene/__init__.py
  setup.py
  tox.ini
Labels: 3.0

#986 Remove six dependency
  graphene/pyutils/compat.py
  graphene/test/__init__.py
  graphene/types/datetime.py
  graphene/types/enum.py
  graphene/types/scalars.py
  graphene/types/utils.py
  graphene/types/uuid.py
  graphene/utils/subclass_with_meta.py
  setup.py
Labels: 3.0

#980 Fix internal link on docs
  docs/types/scalars.rst
Labels: 🐛 bug, 📖 documentation

#971 expose livehtml autobuild in Makefile + Add API autodoc
  .gitignore
  Makefile
  docs/Makefile
  docs/_static/.gitkeep
  docs/api/index.rst
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  graphene/types/argument.py
  graphene/types/context.py
  graphene/types/enum.py
  graphene/types/field.py
  graphene/types/inputfield.py
  graphene/types/inputobjecttype.py
  graphene/types/interface.py
  graphene/types/json.py
  graphene/types/mutation.py
  graphene/types/objecttype.py
  graphene/types/schema.py
  graphene/types/structures.py
  graphene/types/union.py
  graphene/types/unmountedtype.py
  graphene/types/uuid.py
Labels: 📖 documentation

#969 Revise documentation
  UPGRADE-v1.0.md
  UPGRADE-v2.0.md
  docs/execution/dataloader.rst
  docs/execution/execute.rst
  docs/index.rst
  docs/quickstart.rst
  docs/relay/connection.rst
  docs/types/index.rst
  docs/types/interfaces.rst
  docs/types/mutations.rst
  docs/types/objecttypes.rst
  docs/types/scalars.rst
  docs/types/schema.rst
Labels: 📖 documentation

#1002 Remove sponsorship text from readme
  BACKERS.md
  README.md
  ROADMAP.md
Labels: Housekeeping, 📖 documentation

#996 Trying to get codeowners to work
  CODEOWNERS
Labels: Housekeeping
